# Configuration file for the Starship prompt
# See: https://starship.rs/config/

# Don't print a new line at the start of the prompt
add_newline = false

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10


[directory]
truncation_length = 3
truncation_symbol = "â€¦"

[aws]
disabled = true

# Configure battery symbols
[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

#shows when battery below threshold
# "bold red" style when capacity is between 0% and 10%
[[battery.display]]
threshold = 10
style = "bold red"
# "bold yellow" style when capacity is between 10% and 30%
[[battery.display]]
threshold = 30
style = "bold yellow"

#to display the hostname before the character line
[hostname]
ssh_only = false
style = "italic blue"
format = "[$hostname]($style) in "
disabled = false




[git_branch]
symbol = "ğŸŒ¿ "

[git_commit]
disabled = false

[git_status]
conflicted = "âš”ï¸ "
ahead = "ğŸï¸ğŸ’¨ Ã—${count}"
behind = "ğŸ¢ Ã—${count}"
diverged = "ğŸ”± ğŸï¸ ğŸ’¨ Ã—${ahead_count} ğŸ¢ Ã—${behind_count}"
untracked = "ğŸ›¤ï¸  Ã—${count}"
modified = "ğŸ“ Ã—${count}"
staged = "ğŸ—ƒï¸  Ã—${count}"
renamed = "ğŸ“› Ã—${count}"
deleted = "ğŸ—‘ï¸  Ã—${count}"

[python]
pyenv_version_name = false

[conda]
symbol = "ğŸ…’ğŸ "



#The status module displays the exit code of the previous command. 
#The module will be shown only if the exit code is not 0
[status]
disabled = false